





# 1. Hombre (Padre)
# Running
# Basketball
# Fútbol (Soccer)
# Botas
# Mocasines (Casual)
# Industrial (Seguridad)
# Sandalias
# 2. Mujer (Padre)
# Running
# Tacones
# Botas & Botines
# Sandalias
# Plataformas
# Urbanas (Sneakers)
# 3. Niños (Padre)
# Escolares
# Deportivas
# Botas de Lluvia
# Luces LED
# 4. Bebés (Padre)
# No Caminantes
# Primeros Pasos
# Pantuflas
# 5. Marcas (Padre) - Opcional si usas marcas como categorías
# Nike
# Adidas
# Puma
# Vans
# 6. Deportes Específicos (Padre)
# Trekking
# Tenis / Padel
# Golf
# Skateboarding
# 7. Accesorios Calzado (Padre)
# Cordones
# Plantillas
# Productos de Limpieza
# Medias / Calcetines